### ISSUE TITLE
Non unique attributes

### ISSUE THREAD

**Issue by lacrimal** [szechuen/ldif_csv#1]
Spotted that your code works superb however when ldif file contains multiple attributes with same name only one appears. I'm not familiar with C. So it is possible that you can modify your code to  add sufix to consecutive attributes ? objectName, objectName --> objectName, objectName2 etc?

Tremendous job !

**Comment by szechuen** [comment]
Thanks for your compliment. 

I believe the LDIF format does not require keys to be listed in the same order for each record. Hence it may not be wise to add a suffix to duplicated keys in all situations. 

Would appending the elements of duplicated keys to the end of the existing element work? 

i.e. 
duplicatedKey: element1
duplicatedKey: element2

would become duplicatedKey: element1;element2 in CSV

If your use case requires element1 and element2 to be in separate columns, you can then use a spreadsheet program to split them up accordingly.

**Comment by lacrimal** [comment]
Indeed I can use spreadsheet, but then I can use python also ;-)

Anyway - thanks for reply.

**Comment by szechuen** [comment]
If you're looking to parse a large LDIF file fast into the split-column format preferred, I can look into adding an option for that (but it wouldn't be the default).

**Comment by lacrimal** [comment]
In fact i have this solution right now :-)
I'm splitting duplicated keys by coma but at the end i need to import it to database so spited data in column are not exactly what i'm looking for.
This is database so i can do it with pre-processor(shel script) or with pl/sql. I have written some procedure that knows attributes that I'd like to load to table then sort dn to be sure of order and load them in order starting from not null numbering repeating attributes if necessary.

Thanks
